#!/usr/bin/env python
# coding=utf-8
"""
###################################################################

OptiType: precision MHC typing from next-generation sequencing data

###################################################################

Authors: Jiayi Ji; Yexin Zhang
Date: July 2023
Version: 2.1.1




Requirements:
-------------
OptiType uses the following software and libraries:
1) Python 2.7
2) Biopython 1.63
3) Pyomo 4.1
4) Matplotlib 1.3.1
5) Pandas 0.12 (with HDF5 support)
6) HDF5 1.8.11
7) RazerS 3.1
8) Cplex 12.5

Please make sure you have installed said software/libraries
and their dependencies.




Usage:
-------------
1) First filter the read files with the following settings:

>razers3 --percent-identity 90 --max-hits 1 --distance-range 0
         --output-format sam --output sample_fished.sam
         ./data/mhc_reference_dna.fasta sample.fastq

where reference.fasta is either nuc_reference.fasta or gen_reference.fasta
depending on the type of NGS data. The references can be found in the ./data
sub-folder or in the supplementary material. To use the results as input
for OptiType the sam-files have to be converted into fastq format. On Unix-
based operating system you can convert from sam to fastq with the following
command:

>cat sample_fished.sam | grep -v ^@
	| awk '{print "@"$1"\n"$10"\n+\n"$11}' > sample_fished.fastq

For paired-end data pre-process each file individually.

2) After pre-filtering, OptiType can be called as follows:

>python OptiTypePipeline.py -i sample_fished_1.fastq [sample_fished_2.fastq]
                    (--rna | --dna) [--beta BETA] [--enumerate ENUMERATE]
                    --o ./out_dir/

This will produce a CSV with the optimal typing and possible sub-optimal
typings if specified, as well as a coverage plot of the genotype for
diagnostic purposes and a HTML file containing a summary of the results.

>python OptiTypePipeline.py --help
usage: OptiType [-h] --input INPUT [INPUT ...] (--rna | --dna) [--beta BETA]
                [--enumerate ENUMERATE] --outdir OUTDIR [--verbose]



               
python OptiTypePipeline_uu.py -i $fastq1 $fastq2 --dna -v -o $outdir -c $config_file -p $sample_name -b $value

OptiType: Accurate MHC typer

optional arguments:
  -h, --help            show this help message and exit
  --input INPUT [INPUT ...], -i INPUT [INPUT ...]
                        Fastq files with fished HLA reads. Max two files (for
                        paired-end)
  --rna, -r             Specifiying the mapped data as RNA.
  --dna, -d             Specifiying the mapped data as DNA.
  --beta BETA, -b BETA  The beta value for for homozygosity detection.
  --enumerate ENUMERATE, -e ENUMERATE
                        The number of enumerations.
  --outdir OUTDIR, -o   OUTDIR
                        Specifies the out directory to which all files should
                        be written
  --verbose, -v         Set verbose mode on.
"""
from __future__ import print_function
from future import standard_library
standard_library.install_aliases()
from builtins import zip
from builtins import filter
from builtins import map
from builtins import range

## eliminate dependency on an X11 server
#import matplotlib
#matplotlib.use('Agg')

import sys
import subprocess
import os
import argparse
if sys.version_info > (3,0):
    import configparser
else:
    import ConfigParser as configparser
import time
import datetime
import pandas as pd
import hlatyper_uu as ht

import numpy as np
from model_uu import OptiType
from collections import defaultdict

# Try to import pysam, important for RazerS 3 output format
try:
    import pysam
    PYSAM_AVAILABLE = True
except ImportError:
    PYSAM_AVAILABLE = False



def get_num_threads(configured_threads):
  try:
    import multiprocessing
  except (ImportError, NotImplementedError):
    return 2
  if(multiprocessing.cpu_count() < configured_threads):
    return multiprocessing.cpu_count()
  return configured_threads


if __name__ == '__main__':

    this_dir = os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__)))
    config_default = os.path.join(this_dir, 'config.ini')

    parser = argparse.ArgumentParser(description=' OptiType: rabbit MHC typer', prog='OptiType')
    parser.add_argument('--input','-i',
                      nargs='+',
                      required=True,
                      metavar='FQ',
                      help=(".fastq file(s) (fished or raw) or .bam files stored for re-use, generated by "
                          "an earlier OptiType run. One file: single-end mode, two files: paired-end mode.")
                      )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--rna','-r',
                      action="store_true",
                      help="Use with RNA sequencing data."
                      )
    group.add_argument('--dna','-d',
                      action="store_true",
                      help="Use with DNA sequencing data."
                      )
    parser.add_argument('--beta','-b',
                      type=float,
                      metavar='B',
                      default=0.009,
                      help="The beta value for for homozygosity detection (see paper). Default: 0.009. Handle with care."
                      )
    parser.add_argument('--enumerate','-e',
                      type=int,
                      default=1,
                      metavar='N',
                      help=("Number of enumerations. OptiType will output the optimal solution and "
                          "the top N-1 suboptimal solutions in the results CSV. Default: 1")
                      )
    parser.add_argument('--outdir','-o',
                      required=True,
                      help="Specifies the out directory to which all files should be written."
                      )
    parser.add_argument('--prefix', '-p',
                      default=None, dest="prefix", type=str,
                      help="Specifies prefix of output files"
                      )
    parser.add_argument('--verbose','-v',
                      required=False,
                      action="store_true",
                      help="Set verbose mode on."
                      )
    parser.add_argument('--config', '-c',
                      type=argparse.FileType('r'),
                      default=config_default,
                      help="Path to config file. Default: config.ini in the same directory as this script"
                      )

    args = parser.parse_args()

    if not os.path.isfile(args.config.name):
        print ("Config file not found. Place config.ini either alongside this script or use the -c option. "
            "See config.ini.example and note that its fields have changed recently.")
        sys.exit(-1)

    config = configparser.ConfigParser(os.environ)
    config.read(args.config.name)

    unpaired_weight = config.getfloat('behavior', 'unpaired_weight')
    use_discordant = config.getboolean('behavior', 'use_discordant')

    if not os.path.exists(args.outdir):
        os.makedirs(args.outdir)        

    # test if inputs are legit:
    if args.beta < 0.0 or args.beta >= 0.1:
        print("Beta value is not correctly chosen. Please choose another beta value between [0,0.1]")
        sys.exit(-1)

    if args.enumerate <= 0:
        print("The specified number of enumerations must be bigger than %i"%args.enumeration)
        sys.exit(-1)

    if len(args.input) not in (1, 2):
        print("Number of input files can only be 1 (single-end) or 2 (paired-end)")
        sys.exit(-1)


    input_extension = args.input[0].split('.')[-1]

    print(input_extension)
    assert all(ii.endswith('.' + input_extension) for ii in args.input), 'Mixed input file extensions'

    bam_input = (input_extension in ('sam', 'bam', 'SAM', 'BAM'))  # otherwise treated as fastq

    # Constants
    VERBOSE = ht.VERBOSE = bool(args.verbose)  # set verbosity setting in hlatyper too


    #######Yexin: needs to upscale the mismatch tolerance from 97 to 99
    COMMAND = "-i 97 -m 99999 --distance-range 0 -pa -tc %d -o %s %s %s"
    ALLELE_INFO = os.path.join(this_dir, 'data/MHC_alleles_nonpseudo.txt') 
 


    MAPPING_REF = {'gen': os.path.join(this_dir, 'data/mhc_reference_dna_8genes_nontrim_nonpseudo.fasta'),
                   'nuc': os.path.join(this_dir, 'data/mhc_reference_rna.fasta')}
    MAPPING_CMD = config.get("mapping", "razers3") + " " + COMMAND

    date = datetime.datetime.fromtimestamp(time.time()).strftime('%Y_%m_%d_%H_%M_%S')
    if args.prefix == None:
        prefix = date
        out_dir = os.path.join(args.outdir, date)
    else:
        prefix = args.prefix
        out_dir = args.outdir

    if not os.path.exists(out_dir):
        os.makedirs(out_dir)

    if PYSAM_AVAILABLE:
        extension = 'bam'
    else:
        extension = 'sam'

    bam_paths = args.input if bam_input else [os.path.join(out_dir, ("%s_%i.%s" % (prefix, i+1, extension))) for i in range(len(args.input))]


    # SETUP variables and OUTPUT samples
    ref_type = "nuc" if args.rna else "gen"
    is_paired = len(args.input) > 1
    
    out_csv = os.path.join(out_dir, ("%s_result.tsv" % prefix))
    out_plot = os.path.join(out_dir, ("%s_coverage_plot.pdf" % prefix))

    # mapping fished file to reference
    if not bam_input:
        threads = get_num_threads(config.getint("mapping", "threads"))
        if VERBOSE:
          print("\nmapping with %s threads..." % threads)
        for (i, sample), outbam in zip(enumerate(args.input), bam_paths):          
            if VERBOSE:
                print("\n", ht.now(), "Mapping %s to %s reference..." % (os.path.basename(sample), ref_type.upper()))

            subprocess.call(MAPPING_CMD % (threads, outbam,
                                           MAPPING_REF[ref_type], sample), shell=True)

    # sam-to-matrix

    mhc_groups = defaultdict(list)
    allele_length = defaultdict(list)
    with open(ALLELE_INFO) as f:
      for line in f.read().rstrip('\n').split('\n'):
        nbs = int(line.split()[2])
        mhc_type = line.split()[1]
        allele = line.split()[0]
        mhc_groups[mhc_type].append(allele)
        allele_length[allele] = nbs


    if VERBOSE:
        print("\n", ht.now(), "Generating binary hit matrix.")

    if is_paired:
        # combine matrices for paired-end mapping
        pos, read_details = ht.pysam_to_matrix(bam_paths[0])
        binary1 = np.sign(pos)  # dtype=np.uint16
        
        pos2, read_details2 = ht.pysam_to_matrix(bam_paths[1])
        binary2 = np.sign(pos2)  # dtype=np.uint16

        if not bam_input and config.getboolean('behavior', 'deletebam'):
            os.remove(bam_paths[0])
            os.remove(bam_paths[1])
        
        id1 = set(binary1.index)
        id2 = set(binary2.index)
        
 
            
        binary_p, binary_mis, binary_un =  ht.create_paired_matrix(binary1, binary2)

        if binary_p.shape[0] < len(id1) * 0.1:
            print(("\nWARNING: Less than 10%% of reads could be paired. Consider an appropriate unpaired_weight setting "
             "in your config file (currently %.3f), because you may need to resort to using unpaired reads.") % unpaired_weight)

        if unpaired_weight > 0:
            if use_discordant:
                binary = pd.concat([binary_p, binary_un, binary_mis])
            else:
                binary = pd.concat([binary_p, binary_un])
        else:
            binary = binary_p

    else:
        pos, read_details = ht.pysam_to_matrix(bam_paths[0])

        if not bam_input and config.getboolean('behavior', 'deletebam'):
            os.remove(bam_paths[0])

        binary = np.sign(pos)  # dtype=np.uint16



    if VERBOSE:
        print("\n", ht.now(), 'temporary pruning of identical rows and columns')
    unique_col, representing = ht.prune_identical_alleles(binary, report_groups=True)
    representing_df = pd.DataFrame([[a1, a2] for a1, a_l in representing.items() for a2 in a_l],
                                   columns=['representative', 'represented'])

    temp_pruned = ht.prune_identical_reads(unique_col)

    if VERBOSE:
        print("\n", ht.now(), 'Size of mtx with unique rows and columns:', temp_pruned.shape)
        print(ht.now(), 'determining minimal set of non-overshadowed alleles')

    minimal_alleles = ht.prune_overshadowed_alleles(temp_pruned)

    if VERBOSE:
        print("\n", ht.now(), 'Keeping only the minimal number of required alleles', minimal_alleles.shape)

    binary = binary[minimal_alleles]

    if VERBOSE:
        print("\n", ht.now(), 'Creating compact model...')

    if is_paired and unpaired_weight > 0:
        if use_discordant:
            compact_mtx, compact_occ = ht.get_compact_model(binary_p[minimal_alleles],
                pd.concat([binary_un, binary_mis])[minimal_alleles], weight=unpaired_weight)
        else:
            compact_mtx, compact_occ = ht.get_compact_model(binary_p[minimal_alleles],
                binary_un[minimal_alleles], weight=unpaired_weight)
    else:
        compact_mtx, compact_occ = ht.get_compact_model(binary)

    allele_ids = binary.columns


 
    sparse_dict = ht.mtx_to_sparse_dict(compact_mtx)
    threads = get_num_threads(config.getint("ilp", "threads"))               
    if VERBOSE:
        print("\nstarting ilp solver with %s threads..." % threads)
        print("\n", ht.now(), 'Initializing OptiType model...')

    op = OptiType(sparse_dict, compact_occ, mhc_groups, args.beta, 2,
                  config.get("ilp", "solver"), threads, verbosity=VERBOSE)
    result = op.solve(args.enumerate)

    if VERBOSE:
        print("\n", ht.now(), 'Result dataframe has been constructed...')



   

    # write CSV to out. And generate plots
    result.to_csv(out_csv, sep="\t",
                         columns=["A1", "A2", "B1", "B2", "C1", "C2", "D1", "D2","E1", "E2", "F1", "F2", "G1", "G2", "H1", "H2", "I1", "I2", "nof_reads", "obj"],
                         header=["A1", "A2", "B1", "B2", "C1", "C2", "D1", "D2","E1", "E2", "F1", "F2", "G1", "G2", "H1", "H2", "I1", "I2", "Reads", "Objective"])

    hlatype = result.iloc[0].reindex(["A1", "A2", "B1", "B2", "C1", "C2", "D1", "D2","E1", "E2", "F1", "F2", "G1", "G2", "H1", "H2", "I1", "I2"]).drop_duplicates().dropna()


    #features_used = [('gene', 1), ('gene', 2)]
    

    plot_variables = [pos, read_details, pos2, read_details2, (binary_p, binary_un, binary_mis)] if is_paired else [pos, read_details]
    coverage_mat, coverage_mat_count = ht.calculate_coverage(plot_variables, allele_length, hlatype)
    #ht.plot_coverage(out_plot, coverage_mat, table, features, features_used)
    coverage_table = ht.plot_coverage(out_plot, coverage_mat, mhc_groups)
    #ht.count_coverage(out_csv + '.cov', coverage_mat_count, mhc_groups)
    ht.count_coverage_sitewise(out_csv, coverage_mat, mhc_groups)